baseURL = 'https://www.cloudenghub.com/'
languageCode = 'en-us'
title = 'Cloud Engineering Hub'

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

paginate = 10

[params]
  description = 'Community Built for Cloud Engineering enthusiasts to get together, discuss all things cloud technology, and publish tech content.'
  images = ['site-feature-image.jpg']
  title = 'My cool site'

