baseURL = 'https://www.cloudenghub.com/'
languageCode = 'en-us'
title = 'Cloud Engineering Hub'

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""
