[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.89.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.89.3"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.89.3"
